name: Daily Jobs & News Digest

on:
  schedule:
    # 02:30 UTC = 08:00 IST
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Twilio WhatsApp test ping
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
        run: |
          curl -sS -X POST "https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json" \
            --data-urlencode "From=${TWILIO_WHATSAPP_FROM}" \
            --data-urlencode "To=${WHATSAPP_TO}" \
            --data-urlencode "Body=Test from GitHub Actions ✅" \
            -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}"

      - name: Run once
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          SMTP_GMAIL_USER: ${{ secrets.SMTP_GMAIL_USER }}
          SMTP_GMAIL_APP_PASSWORD: ${{ secrets.SMTP_GMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python scripts/main.py --once
